export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_ERROR = "SET_ERROR";

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAILURE = "PURCHASE_BURGER_FAILURE";
export const SET_PURCHASING = "SET_PURCHASING";
export const RESET_ORDER = "RESET_ORDER";
export const FETCH_PREV_ORDERS = "FETCH_PREV_ORDERS";
export const SET_PREV_ORDERS = "SET_PREV_ORDERS";
